import { Component, OnInit } from '@angular/core';
import { StringBuilder,ProfileFactoryType,ContextManager,Convert,AppActivity } from 'epma-platform/services';
import { Level, ProfileContext, OnProfileResult, IProfileProp,Byte, Decimal, decimal, Double, Float, Int64, long, Long, StringComparison } from 'epma-platform/models';
import { AppDialog } from 'epma-platform/controls';
import { HelperService} from 'epma-platform/soapclient';
import 'epma-platform/stringextension';
import DateTime from 'epma-platform/DateTime';
import TimeSpan from 'epma-platform/TimeSpan';
import { MessageEventArgs, MessageBoxResult, iMessageBox, MessageBoxButton, MessageBoxType, MessageBoxDelegate } from 'epma-platform/services';
import { ObjectHelper } from 'epma-platform/helper';
  
    export class CConstants {
        public static WeightCode: string = "CC_MEDWEIGHT";
        public static HeightCode: string = "CC_MEDHEIGHT";
        public static DayCode: string = "CC_MEDDRSN1";
        public static MonthCode: string = "CC_MEDRSN3";
        public static YearCode: string = "CC_MEDRSN4";
        public static WeekCode: string = "CC_MEDDRSN2";
        public static WeekDuration: number = 7;
        public static MonthDuration: number = 30;
        public static YearDuration: number = 365;
        public static AMENDED: string = "MEDStatus1";
        public static CANCELLED: string = "MEDStatus2";
        public static DISCONTINUED: string = "MEDStatus3";
        public static ISSUED: string = "MEDStatus4";
        public static DISPENSED: string = "MEDStatus5";
        public static SUBMITTED: string = "MEDStatus6";
        public static AWAITINGAUTHORISE: string = "MEDStatus7";
        public static AUTOVERIFIED: string = "MEDStatus9";
        public static CLINICALLYVERIFIED: string = "MEDStatus10";
        public static TECHNICALLYVALIDATED: string = "MEDStatus11";
        public static NOTAUTHORISED: string = "MEDStatus12";
        public static ONHOLD: string = "MEDStatus13";
        public static COMPLETED: string = "MEDStatus14";
        public static LongDateFormat: string = "dd-MMM-yyyy hh:mm:ss";
        public static LongDateListFormat: string = "dd-MMM-yyyy HH:mm:ss";
        public static ShortDateFormat: string = "dd-MMM-yyyy";
        public static ConflictDateFormat: string = "dd-MMM-yyyy HH:mm:00";
        public static TimeFormat: string = "HH:mm";
        public static DateHMFormat: string = "dd-MMM-yyyy HH:mm";
        public static DateFormat: string = "dd-MMM-yyyy";
        public static MaxNoOfPrescriptions: number = 40;
        public static SNOMED_CT: string = "SNOMED CT";
        public static CANCELRSN1: string = "Prescribed in error";
        public static CANCELRSN2: string = "Entered in error";
        public static TRUE: string = "true";
        public static FALSE: string = "false";
        public static cONE: string = '1';
        public static cZERO: string = '0';
        public static sVisible: string = "Visible";
        public static sNormalDisplaytext: string = "Normal";
        public static sTitratedDisplaytext: string = "Titrated";
        public static ACTIVITY_AUTHORISE: string = "AUTHORISE";
        public static ACTIVITY_NOT_AUTHORISE: string = "NOTAUTHORISE";
        public static ACTIVITY_CLINICALLYVERIFY: string = "CLINICALLYVERIFY";
        public static ClinicallyVerifyMenuSL: string = "MN_MED_VERIFY_SL_P2";
        public static OutEnc: string = "CC_OUTPAT";
        public static ClinicallyVerifyMenu: string = "MN_MED_VERIFY_P2";
        public static AuthoriseMenuSL: string = "MED_CA_AUTHORISE_SL_P2";
        public static AuthoriseMenu: string = "MED_CA_AUTHORISE_P2";
        public static AuthoriseMenuCode: string = "MN_MED_AUTHORI_SL_P2";
        public static ClinicallyVerifyMenuCode: string = "MED_CA_CLN_VRFY_SL_P2";
        public static OutPatientPrescribeMenuCode: string = "MN_MEDOUTPATSL_P2";
        public static DischargePrescribeMenuCode: string = "MN_MEDDISCHRGESL_P2";
        public static ClerkingPrescribeMenuCode: string = "MN_MEDCLERKSL_P2";
        public static LeavePrescribeMenuCode: string = "MN_MEDLEAVESL_P2";
        public static InpatientPrescribeMenuCode: string = "MN_MEDINPATSL_P2";
        public static ForadminPrescribeMenuCode: string = "MN_MEDADMINISTRAT_P2";
        public static TechnicallyValidateMenuCode: string = "MN_MED_VALIDATE_S_P2";
        public static Activity_Discontinue: string = "CC_MEDDISCONTINUE";
        public static Activity_Cancel: string = "CC_MEDCANCEL";
        public static Dispensingcode: string = "CC_DISPINSTR";
        public static ActionCACode: string = "Amend";
        public static CodingSchemeName: string = "LORENZO";
        public static Version: string = "1.0";
        public static FilterType: string = "A";
        public static More: string = "More";
        public static NO_REPLACEMENT: string = "There are no replacement drugs available for this medication item<{0}>. Choose any appropriate medication item to proceed";
        public static No_Replacement_Current_Version: string = " is not available as part of current version. Please reselect another from medication search list";
        public static REPLACEMENT_ITEMS: string = "This medication item<{0}> has been de-activated. Choose one the following replacement drugs if needed";
        public static MedicationMgmt: string = "M_Mgmt";
        public static ManagePrescription: string = "M_Presc";
        public static QueryCareEvents: string = "M_Enc";
        public static ReferenceWS: string = "M_Ref";
        public static TermWS: string = "M_Term";
        public static CBCFormWS: string = "M_CBCForm";
        public static ProblemWS: string = "M_Problem";
        public static AllergyWS: string = "M_Allergy";
        public static TeamMgmtWS: string = "M_TeamMgmt";
        public static Formulary_Drug: string = "CC_DRUG";
        public static Formulary_Appliance: string = "CC_APPLIANCE";
        public static Formulary_Unknown: string = "CC_UNKNOWN";
        public static Other: string = "CC_OTHER";
        public static OtherFreeText: string = "CC_OTHER_FREETEXT";
        public static CATALOGUEITEM: string = "CATALOGUEITEM";
        public static VIRTUALPRODUCT: string = "VIRTUALPRODUCT";
        public static VIRTUALPRODUCTPACK: string = "VIRTUALPRODUCTPACK";
        public static ACTUALMOIETY: string = "ACTUALMOIETY";
        public static ACTUALPRODUCT: string = "ACTUALPRODUCT";
        public static ACTUALPRODUCTPACK: string = "ACTUALPRODUCTPACK";
        public static EncountersPageSize: number = 20;
        public static SUBTYPE: string = "CC_MULCMPNTITM";
        public static SUBTYPE_GAS: string = "CC_MEDGAS";
        public static SUBTYPE_BLOOD: string = "CC_BLDPRODT";
        public static ISOXYGENFORMVIEW: string = "OXYGENFORMVIEW";
        public static HighRisk: string = "High risk";
        public static AllProducts: string = "All products";
        public static SomeProducts: string = "Some products";
        public static HighRisk_CC: string = "CC_HIGHRISK";
        public static AllChild_CC: string = "CC_OCCRALLCHILD";
        public static SomeChild_CC: string = "CC_OCCRSOMECHILD";
        public static ForAdministration: string = "CC_FRADMINSTN";
        public static Administered: string = "Administered";
        public static Precatalog: string = "PRESCRIPTIONNONCATALOGUE";
        public static Fordrug: string = "formulary drug";
        public static NonCatitem: string = "non-catalogue item";
        public static sPimport: string = "CC_PIMPORT";
        public static DRUGDUPLICATION: string = "CC_DUPL_CHK";
        public static DRUGALLERGY: string = "CC_DRUG_ALLERGY";
        public static DRUGCONTRA: string = "CC_DRUG_CONTRA";
        public static DRUGINTRACT: string = "CC_INTERACTIONS";
        public static DRUGWARNING: string = "CC_DRUG_WARNING";
        public static DRUGPRECAUTION: string = "CC_DRUG_PRECAUTION";
        public static WBTYPE: string = "Type 5";
        public static WeeklyFrq: string = "WEEKLY";
        public static SelectReason: string = "Select reason";
        public static CONST_DEF_GROUPBY: string = "DRUG";
        public static sInteract: string = "Drug interaction";
        public static sDuplication: string = "Drug duplication";
        public static sAllergy: string = "Drug allergy";
        public static sMandatory: string = "Drug mandatory";
        public static sContraIndication: string = "Drug contraindication";
        public static sDrugContraIndication: string = "Contraindication";
        public static sContraindicationcheck: string = "Contraindication check";
        public static sDrugInt: string = "Drug interaction";
        public static sDrugDup: string = "Drug duplication";
        public static sDrugAlg: string = "Drug allergy";
        public static sSubDupDouble: string = "Doubling";
        public static sSubDupIngredient: string = "Ingredient";
        public static sSubDupHierarchy: string = "Hierarchy";
        public static sSubAllergyIng: string = "Ingredient";
        public static sSubAllergyCross: string = "Cross reactor group";
        public static sSubAllergyClass: string = "Ingredient class group";
        public static sSubAllergyNotIncluded: string = "Allergen(s) not included in check";
        public static CON_PROBLEM: string = "Your patient has {0} designated on their problem list. {1} is contraindicated due to: {2}.";
        public static CON_PROCEDURE: string = "Your patient has {0} performed on {1} designated on their procedure list. {2} is contraindicated due to: {3}.";
        public static CON_RPROBLEM: string = "Your patient has {0} designated on their problem list. This may be related to {2}. {1} is contraindicated in {2}.";
        public static CON_RPROCEDURE: string = "Your patient has {0} performed on {1} designated on their procedure list. This may be related to {3}. {2} is contraindicated in {3}.";
        public static VM_ALLCHILD: string = "All {0} products are contraindicated due to: {1}.";
        public static VM_RALLCHILD: string = "This may be related to {1}. {0} products are contraindicated in {1}.";
        public static VM_SOMECHILD: string = "Some {0} products are contraindicated due to: {1}. Check ~monograph~ of intended product before prescribing.";
        public static VM_RSOMECHILD: string = "This may be related to {1}. Some {0} products are contraindicated in {1}. Check ~monograph~ of intended product before prescribing.";
        public static VM_PROBLEM: string = "Your patient has {0} designated on their problem list. {1}";
        public static VM_PROCEDURE: string = "Your patient has {0} performed on {1} designated on their procedure list. {2}";
        public static SPECIFIC1: string = "Your patient has {0} designated on their problem list. {1} has the precaution: {2}.";
        public static SPECIFIC2: string = "Your patient has {0} performed on {1} designated on their procedure list. {2} has the precaution: {3}.";
        public static RELATED1: string = "Your patient has {0} designated on their problem list. This may be related to {1}. Precautions exist for: {1}.";
        public static RELATED2: string = "Your patient has {0} performed on {1} designated on their procedure list. This may be related to {2}. Precautions exist for: {2}.";
        public static ALLCHILD1: string = "Precautions exist for all {0} products. Check ~monograph~ of intended product before prescribing.";
        public static ALLCHILD2: string = "Precautions exist for some {0} products. Check ~monograph~ of intended product before prescribing.";
        public static RELATED3: string = "This may be related to {1}. Precautions exist for all {0} products. Check ~monograph~ of intended product before prescribing.";
        public static RELATED4: string = "This may be related to {1}. Precautions exist for some {0} products. Check ~monograph~ of intended product before prescribing.";
        public static SPECIFIC5: string = "Your patient has {0} designated on their problem list. The following specific condition warnings apply to {1} : {2}.";
        public static SPECIFIC6: string = "Your patient has {0} performed on {1} designated on their procedure list. The following specific condition warnings apply to {2} : {3}.";
        public static RELATED7: string = "Your patient has {0} designated on their problem list. The following related condition warnings apply to {1} : {2}.";
        public static RELATED8: string = "Your patient has {0} performed on {1} designated on their procedure list. The following related condition warnings apply to {2} : {3}.";
        public static ALLCHILD3: string = "all {0} products. Check ~monograph~ of intended product before prescribing.";
        public static ALLCHILD4: string = "some {0} products. Check ~monograph~ of intended product before prescribing.";
        public static SPECIFIC7: string = "Your patient has {0} designated on their problem list. Warnings apply for specific conditions for {1}";
        public static SPECIFIC8: string = "Your patient has {0} performed on {1} designated on their procedure list. Warnings apply for specific conditions for {2}";
        public static RELATED9: string = "Your patient has {0} designated on their problem list. Warnings apply for related conditions for {1} ";
        public static RELATED10: string = "Your patient has {0} performed on {1} designated on their procedure list. Warnings apply for related conditions for {2}";
        public static MONOGRAPH: string = " <a href='../MedicationMgmt/Views/MedDrugMonograph.aspx'> <font color= #000099  style= text-decoration:underline ><b>monograph</b></font></a>";
        public static sAllergyNotIncludedMsg: string = "The following recorded allergen(s) for this patient {0} have not been included in the allergy checking";
        public static SUBDUPDBLFRMTFORCURRMED: string = "The patient is already receiving an equivalent product in their existing medication. {0} Prescribed on: {1}";
        public static SUBDUPDOUBLEFORMAT: string = "The patient is already receiving an equivalent product in their existing medication. {0}";
        public static SUBDUPINGREDIENTFORMAT: string = "You are about to prescribe {0}. This contains the same ingredient {1}, as one or more items already prescribed for your patient: {2} Prescribed on: {3}";
        public static SUBDUPINGFRMTFORCURRMED: string = "You are about to prescribe {0}. This contains the same ingredient {1}, as one or more items already prescribed for your patient: {2}";
        public static SUBDUPHIERARCHYFORMAT: string = "The patient is already receiving one or more products of the same hierarchy {0} in their existing medication/current prescription. {1} Prescribed on: {2}";
        public static SUBDUPHRCHYFRMTFORCURRMED: string = "The patient is already receiving one or more products of the same hierarchy {0} in their existing medication/current prescription. {1}";
        public static SUBALLERGYINGFORMAT: string = "Patient record shows potential sensitivity to {0}. You have selected {1} which contains {2} from the same group {3}. Reaction: {4}. Severity {5}.";
        public static SUBALLERGYCROSSFORMAT: string = "Patient record shows potential sensitivity to {0}. You have selected {1} which contains {2} for which cross- sensitivity reactions may occur. Reaction: {3}. Severity {4}.";
        public static SUBALLERGYINGGFORMAT: string = "Patient record shows potential sensitivity to {0}. You have selected {1} which contains {2}. Reaction: {3}. Severity {4}.";
        public static sPrecaution: string = "Precaution";
        public static sWarning: string = "Warning";
        public static sDrugInter: string = "DRUGINT";
        public static sDrugDupli: string = "DRUGDUP";
        public static sDrugAlger: string = "DRUGALG";
        public static sAbsolute: string = "Always show";
        public static sRelated: string = "Related";
        public static sSpecific: string = "Specific";
        public static sIntractonLow: string = "LOWWW";
        public static sIntractonMedium: string = "CC_MODERATE";
        public static sIntractonHigh: string = "HIGHH";
        public static sBehaviourType1: string = "CC_BEHTYPE_1";
        public static sBehaviourType2: string = "CC_BEHTYPE_2";
        public static sBehaviourType3: string = "CC_BEHTYPE_3";
        public static sBehaviourType4: string = "CC_BEHTYPE_4";
        public static sBehaviourType5: string = "CC_BEHTYPE_5";
        public static sAllChilds: string = "CC_OCCRALLCHILD";
        public static sSomeChilds: string = "CC_OCCRSOMECHILD";
        public static sGeneric: string = "Generic";
        public static NONCATALOGUEITEM: string = "NONCATALOGUEITEM";
        public static RECONCILED: string = "Reconciled";
        public static RECONCILEDSTOPPED: string = "Stopped";
        public static NOTRECONCILED: string = "NotReconciled";
        public static sMedClerk: string = "CC_MEDCLERK";
        public static Supplycode: string = "CC_SUPPLY";
        public static DonotSupplycode: string = "CC_MEDDONTSUPPLY";
        public static Bolus: string = "Bolus";
        public static Booster: string = "Booster";
        public static ConcentrationDoseUOM: string = "ConcentrationDoseUOM";
        public static TypeInInfusionRateNumerator: string = "TypeInInfusionRateNumerator";
        public static RouteOptionCode: string = "RouteName";
        public static QtyUOMoptioncode: string = "QTYALLUOM";
        public static DoseUOMOptionCode: string = "ToDoseUOM";
        public static RecordadminDoseUOMOptionCode: string = "Recordadmindoseuom";
        public static FormOptionCode: string = "FormName";
        public static FrequencyOptionCode: string = "FrequencyName";
        public static AdminOptionCode: string = "AdminInstruction";
        public static SiteOptionCode: string = "Site";
        public static RecordAdminSiteOptionCode: string = "RecordAdminSite";
        public static Clerking: string = "CC_MEDCLERK1";
        public static Discharge: string = "CC_DSCHRG";
        public static SecondaryScreen: string = "SECONDARYSCREEN";
        public static OnceOnlyFrequency: string = "CC_IPONCENLY";
        public static CONST_QUANTITY: string = "CC_QUANTITY";
        public static PeriodFrequency: string = "CC_PERIOD";
        public static CONST_DOSE: string = "CC_DOSE";
        public static CONST_ADMINMETHOD: string = "CC_ADMN_METHOD";
        public static CONST_MORE: string = "CC_More";
        public static OverdueToNotknownTime: number = 72;
        public static SlotStatusPlanned: string = "CC_PLANNED";
        public static PatConf_Pres: string = "CC_PCPRES";
        public static PatConf_Problem: string = "CC_PCPRB";
        public static Event: string = "Event ";
        public static sDose: string = "Dose ";
        public static nLockingDuration: number = 5;
        public static MULTIROUTEDILIMITER: string = "/ ";
        public static MULTIROUTE_ROUTES: string = '|';
        public static MULTIROUTE_ROUTE: string = '~';
        public static MULTIROUTEOIDDILIMITER: string = ",";
        public static MULTICOMPONENT_SPLIT: string = '^';
        public static MCI_Deactivate: string = " have been deactivated since they were prescribed. Please discontinue/cancel accordingly";
        public static MCI_DeactReorder: string = " have been deactivated since they were prescribed. Please reselect another medication item to proceed";
        public static Orderset: string = "ORDERSET";
        public static SelProdLink: string = "Select Product";
        public static NOObservationandResult: string = "There are no observations or results configured for prescription item ";
        public static CAMEDFORADM: string = "CC_FOR_ADMIN";
        public static CAMEDCLERK: string = "MN_MEDCLERKSL";
        public static CAMEDDISCHARGE: string = "MN_MEDDISCHRGESL";
        public static CAMEDLEAVE: string = "MN_MEDLEAVESL";
        public static CAMEDINPAT: string = "MN_MEDINPATSL";
        public static SelectBrand: string = "Select brand";
        public static Selectproduct: string = "Select product";
        public static ADHOC_ITEM_LORENZOID: string = "PI-001";
        public static ADHOC_ITEM_NAME: string = "Multiple component item";
        public static ml: string = "UOM-25";
        public static litre: string = "UOM-7";
        public static hour: string = "UOM-46";
        public static minute: string = "UOM-43";
        public static second: string = "UOM-42";
        public static month: string = "UOM-49";
        public static year: string = "UOM-50";
        public static CompositeUOM: string = "compound";
        public static PrescribedOPtionList: string = "The below items are present in the {0} list. Please select the appropriate item from the list. ";
        public static PrescribedOptionListOverride: string = "The below items exist in the {0} medication list and may match with the item you are currently prescribing. Please select appropriate item from the list if it can be mapped to the {1} medication you are prescribing. If there is no matching item, please select No matches in the {0} list to override and Click Ok to continue. ";
        public static sDischargeOverride: string = "discharge";
        public static lblNoMatch_txt: string = "No matches in {0} list";
        public static lblClercked: string = "clerked";
        public static sPrescribedOptWindowTitle: string = "Entries in {0} list";
        public static sDischargePrescription: string = "discharge prescription";
        public static sInpatientPrescription: string = "inpatient prescription";
        public static sClerking: string = "medication clerking";
        public static SourceDataProvider: string = "CC_DATAPROVIDER";
        public static ErrMsgOverrideIndicationRsn: string = "Please choose a reason for overriding indications";
        public static StaticFormName: string = "Default";
        public static Supplycomments: string = "CC_SupplyComments";
        public static Addtionalcomments: string = "CC_Additional";
        public static RecordedWeightConceptCode: string = "CC_RBW";
        public static IBWConceptCode: string = "CC_IBW";
        public static ABWConceptCode: string = "CC_ABW";
        public static OtherInstruction: string = "Other instruction(s)";
        public static sAuthoriseText: string = " - " + "Needs authorisation";
        public static sAuthoriseWaiting: string = "Awaiting authorisation";
        public static sMCAuthoriseText: string = "One or more components require authorisation";
        public static DailyDose: string = "CC_MED_DLYDOSE";
        public static PerDose: string = "CC_MED_PERDOSE";
        public static DateTimeMinYear: number = 1753;
        public static DateTimeMaxYear: number = 9999;
        public static QtyScale: number = 5;
        public static QtyPrecision: number = 3;
        public static TitratedgridSize: number = 7;
        public static NO_OF_MINUTESPER_HOUR: number = 60;
        public static NO_OF_HOURSPER_DAY: number = 24;
        public static NO_OF_DAYSPER_WEEK: number = 7;
        public static NO_OF_DAYSPER_MONTH: number = 30;
        public static NO_OF_DAYSPER_YEAR: number = 365;
        public static NO_OF_MINUTESPER_DAY: number = 1440;
        public static Type1: string = "Type 1";
        public static Type2: string = "Type 2";
        public static Type3: string = "Type 3";
        public static Type4: string = "Type 4";
        public static Type5: string = "Type 5";
        public static Selectreason: string = "Select reason";
        public static Selectreasonstar: string = "Select reason*";
        public static DrugPropertyCNTRLDDRUG: string = "CC_CNTRLDDRUG";
        public static DischargeDsplyTxt: string = "discharge";
        public static clerkDsplyTxt: string = "clerked";
        public static leaveDsplyTxt: string = "leave";
        public static OPDsplyTxt: string = "outpatient";
        public static sTitratedgrdcolumnNamefrClk: string = "Enter {0} doses taken";
        public static sTitratedgrdcolumnName: string = "Enter {0} doses";
        public static sTimeHeaderName: string = "Time(s)";
        public static UOMType1: string = "CC_MEDDRSN1";
        public static WeeklyFreq: string = "CC_MEDDRSN2";
        public static UOMType2: string = "CC_MEDDRSN2";
        public static UOMType3: string = "CC_MEDRSN3";
        public static UOMType4: string = "CC_MEDRSN4";
        public static UOMType5: string = "CC_MINUTES";
        public static UOMType6: string = "CC_HOURS";
        public static IntervalFreq: string = "CC_INTERVAL";
        public static AsDirectedLZOID: string = "FRC-001";
        public static WhenRequiredLZOID: string = "FRQ-88";
        public static sDrugrndtime: string = "Drugroundtime";
        public static sFixedTime: string = "FixedTime";
        public static sIsHavingtime: string = "1";
        public static sIsHavingtimeZero: string = "0";
        public static sEvent: string = "Event";
        public static REVIEWTITRATED: string = "REVIEWTITRATED";
        public static TBD: string = "TBD";
        public static HRAText: string = "Prescriptionitem";
        public static InpatientEncounter: string = "CC_INPAT";
        public static OutPatientEncounter: string = "CC_OUTPAT";
        public static EmergencyEncounter: string = "CC_ACCEM";
        public static EncStatusOpen: string = "CC_ENCOPEN";
        public static Permissionpresdrugs: string = "PM_PRESC_DRGS";
        public static permissionpresdrugsdesc: string = "Can prescribe drugs";
        public static DoseUOM_Type_Each: string = "each";
        public static DoseUOM_Type_Volumn: string = "volume";
        public static ChangingDose: string = "Changing dose";
        public static Infinity: string = "Infinity";
        public static NaN: string = "NaN";
        public static sawaitingauthHeader: string = "Awaiting authorisation";
        public static sCancelled: string = "CANCELLED";
        public static sCompDisc: string = "COMPLETED/DISCONTINUED";
        public static sAUTHORISE: string = "AWAITING AUTHORISATION";
        public static CompletedByPrescriber: string = "CC_COMPLEBYPRESCRBER";
        public static CompletedByPharmacist: string = "CC_PRESCOMPLPHARM";
        public static InProgress: string = "CC_INPROGRESS";
        public static ChangingDoseMezzanineDaywiseWidth: number = 1115;
        public static ChangingDoseMezzanineNonDaywiseWidth: number = 330;
        public static ChangingDoseColumnHeader: string = "Dose";
        public static Changingdose: string = "Changing dose";
        public static AsNeeded: string = "As needed";
        public static SVActionAdd: string = "Add";
        public static SVActionUpdate: string = "Update";
        public static SVActionChangingDose: string = "ChangingDose";
        public static SVActionFormViewerOk: string = "FormViewerOk";
        public static OnceOnlyLZOID: string = "FRC-002";
        public static NoOfDaysInMonth: number = 28;
        public static GenReview: string = "CC_GENREW";
        public static OmitDosReview: string = "CC_OMTREW";
        public static NewSequenceCode: string = "0";
        public static FormViewerIconImage: string = "FormViewerIconImage";
        public static FormViewerReviewIconImage: string = "FormViewerReviewIconImage";
        public static ParacetamolIngredientLorenzoID: string = "IN-1129";
        public static AnyParacetamolAdministrationCheckInHours: number = 4;
        public static ORSAllow: string = "CC_ALLOWADJUST";
        public static ORSAllowAndPreselect: string = "CC_ALLOWPRESELCT";
        public static NOT_EXIST_DRCDATA: string = "10001";
        public static NODRCDATA: string = "CC_NODRCFDB1A";
        public static GPC_ERRORCODEDRUGNOTEXISTS: number = 9000001;
        public static GPC_ERRORCODETRANSFORMGPCONNOTEXISTS: number = 9000002;
        public static TABGPCONNECT: string = "GPCONNECT";
        public static CancelSupplycode: string = "CC_CanMedreq";
        public static MedDispenseRequestSent: string = "CC_MEDCLMSREQSENT";
        public static MedDispenseIssued: string = "CC_MEDCLMSISSUED";
        public static MedDispenseCancelled: string = "CC_MEDCLMSCANC";
        public static MedDispenseCancelledEPR: string = "CC_MEDCLMSCANCEPR";
        public static DRCBehaviourType5: string = "CC_BEHTYPE_5";
        public static DRCBehaviourType4: string = "CC_BEHTYPE_4";
        public static ClosedEncounterCode: string = "CC_ENCCLOSED";
    }
    export class WscDispenseStatus {

    }
    export class ControType {
        public static StartDate: string = "Date";
        public static Frequency: string = "Frequency";
        public static DoseType: string = "DoseType";
    }
    export class ValueSet {
        public static RVPeriodUOM: string = "MEDDRSN_RVP";
    }
    export class ClerkFormViewDefault {
        public static LaunchFormNoMandatory: string = "CC_FRMVWRNOMAND";
        public static LaunchFormMandatory: string = "CC_FRMVWRMAND";
        public static DoNotLaunchForm: string = "CC_DNTLCHFRMVWR";
    }
    export class ValueDomain {
        public static SupplyInstruction: string = "MEDSUPPLYIN";
        public static Itemstatus: string = "MEDPITSTC";
        public static DispensingInstruction: string = "DISPINS";
        public static Contyp: string = "CNFTY";
        public static DrugDuplication: string = "SUBDP";
        public static DrugAllergy: string = "SUBAG";
        public static DrugContra: string = "SUBCI";
        public static Severity: string = "MEDSVRTY";
        public static Comments: string = "WARSN";
        public static TreatmentToContinue: string = "MEDTRTCONTINUE";
        public static ReasonForModification: string = "MRSN";
        public static Duration: string = "MEDDRSN";
        public static HoldReason: string = "MEDHOLDREASON";
        public static DoseType: string = "MEDDOSEFRM";
        public static MedicationAdministrationSlotStatus: string = "MASLOTSTATUSCODE";
        public static ForAdminDoseType: string = "MEDDOSE";
        public static MEDCATREASON: string = "MEDCATREASON";
        public static ConDose: string = "MEDDBSAFR";
        public static Month: string = "EXPMONTHS";
        public static MedicationClerking: string = "MEDCLRSOR";
        public static InstallIns: string = "INSTALINS";
        public static MedicationEncounterPrep: string = "MEDENPRP";
        public static ReconcileReason: string = "MEDCANDISCNTRSN";
        public static ConflictsReason: string = "WARSN";
        public static EndorsementProperties: string = "MEDENPRP";
        public static ProductType: string = "PRODUCTTYPE";
        public static MedicationOcInPrd: string = "MedOcInPrd";
        public static MedClerkModificationReasons: string = "MEDCLERKING";
        public static InstallVDur: string = "MEDINSTLINTVDUR";
        public static CONST_OVERRIDE_REASON: string = "OVERIDEREASON";
        public static RM_UNIT_MEASURE: string = "RM_UNIT_MEASURE";
        public static SUBINT: string = "SUBINT";
        public static BHVTY: string = "BHVTY";
        public static INFUSIONTYPE: string = "INFUSIONTYPE";
        public static RANGEOPERATOR: string = "RANGEOPERATOR";
        public static INFROUNDTO: string = "INFROUNDTO";
        public static HUMIDIFICATION: string = "HUMIDIFICATION";
        public static DRCErrorCode: string = "DRCErrorCode";
        public static INDICATIONOVRDREASON: string = "OVRDREASON";
        public static DRCACKREASON: string = "DRCACKWRSN";
        public static PRESTYPE: string = "IPPMAPRCTYP";
        public static TITRATEDDOSEINSTRUCTION: string = "TITRDSINST";
        public static Supplystatus: string = "MEDSUPPLYSTATUS";
        public static MEDURGENCY: string = "MEDURGENCY";
    }
    export class InfusionTypesCode {
        public static CONTINUOUS: string = "CC_IPPINFTYPCON";
        public static INTERMITTENT: string = "CC_IPPINFTYPINTE";
        public static PCA: string = "CC_IPPINFTYPPCA";
        public static SINGLEDOSEVOLUME: string = "CC_IPPINFTYPSNGDOSE";
        public static FLUID: string = "CC_FLUID";
        public static SUBTYPE_GAS: string = "CC_MEDGAS";
    }
    export class DoseTypeCode {
        public static NORMAL: string = "CC_MEDDOSE4";
        public static VARIABLE: string = "MEDDOSE1";
        public static STEPPED: string = "MEDDOSE2";
        public static DOSAGERANGE: string = "MEDDOSE17";
        public static CONDITIONAL: string = "CC_CONDNLDSNG";
        public static TITRATED: string = "CC_TITRATED";
        public static STEPPEDVARIABLE: string = "CC_STEPPEDVARIABLE";
        public static NORMALDisplaytxt: string = "Normal";
    }
    export class DRCDoseTypes {
        public static Maintenance: string = "DDT-1";
        public static Single: string = "DDT-2";
        public static Loading: string = "DDT-3";
        public static Initial: string = "DDT-4";
        public static Test: string = "DDT-5";
        public static Titration: string = "DDT-6";
        public static Prophylactic: string = "DDT-7";
        public static Systemdefined: string = "SDDT-0";
        public static General: string = "DDT-0";
    }
    export class PrescriptionTypes {
        public static Clerking: string = "CC_MEDCLERK1";
        public static Outpatient: string = "CC_MED_TYP_OP";
        public static ForAdministration: string = "CC_FOR_ADMIN";
        public static Leave: string = "CC_Patientleave";
        public static Discharge: string = "CC_DSCHRG";
        public static Inpatient: string = "CC_FOR_ADMIN";
        public static Foradministration: string = "For administration";
        public static sInpatient: string = "Inpatient";
        public static GPConnect: string = "GPConnect";
    }
    export class PrescriptionItemStatusCodes {
        public static AMENDED: string = "MEDStatus1";
        public static CANCELLED: string = "MEDStatus2";
        public static DISCONTINUED: string = "MEDStatus3";
        public static ISSUED: string = "MEDStatus4";
        public static DISPENSED: string = "MEDStatus5";
        public static SUBMITTED: string = "MEDStatus6";
        public static AWAITINGAUTHORISE: string = "MEDStatus7";
        public static AUTOVERIFIED: string = "MEDStatus9";
        public static CLINICALLYVERIFIED: string = "MEDStatus10";
        public static TECHNICALLYVALIDATED: string = "MEDStatus11";
        public static NOTAUTHORISED: string = "MEDStatus12";
        public static ONHOLD: string = "MEDStatus13";
        public static COMPLETED: string = "MEDStatus14";
    }
    export class CAActivity {
        public static CA_PRESCRIBE: string = "Prescribedrugs";
        public static CA_AUTHORISE: string = "AUTHORISE";
        public static CA_NOTAUTHORISE: string = "NOTAUTHORISE";
        public static CA_CLNVERIFY: string = "CLINICALLYVERIFY";
        public static CA_AMEND: string = "AMEND";
        public static CA_REORDER: string = "REORDER";
        public static CA_CANCELDISCONTINUE: string = "CANCELDISCONTINUE";
        public static CA_TECHVALIDATE: string = "TECHVALIDATE";
        public static CA_UNHOLD: string = "UNHOLD";
        public static CA_HOLD: string = "HOLD";
        public static CA_VWFLTERPRES: string = "View and Filter Prescription";
        public static OnlyConflictsUpdate: string = "Update conflicts";
        public static PRECAUTION: string = "Precaution";
        public static CONTRAINDICATION: string = "Drug contraindication";
        public static WARNING: string = "Warning";
        public static sAlways: string = "CC_SUBCI_ALWAYS";
        public static sRelated: string = "CC_SUBCI_RELATED";
        public static sSpecific: string = "CC_SUBCI_SPECIFIC";
        public static sGeneric: string = "Generic";
        public static RECONCILED: string = "Reconciled";
        public static RECONCILEDSTOPPED: string = "Stopped";
        public static NOTRECONCILED: string = "NotReconciled";
        public static CA_RECONCILED: string = "RECONCILED";
        public static CA_UPDATEDRUGS: string = "UpdateDrugs";
        public static CA_UPDATE_SEQ_DRUGS: string = "UpdateSequentialDrugs";
        public static CA_UPDATE_NONIVSEQ_DRUGS: string = "UpdateNonIVSequentialDrugs";
        public static NonIVSeqUpdForSubsequentItems: string = "NonIVSeqUpdForSubsequentItems";
        public static OnlyDRCConflictsUpdate: string = "Update DRCConflicts";
        public static SequentialActionCodeAEITS: string = "AddExistingItemToSequence";
    }
    export class CMedConstants {
        public static CA_AUTHORISE: string = "MED_CA_AUTHORISE_P2";
        public static CA_CLNVERIFY: string = "MED_CA_CLN_VRFY_P2";
        public static CA_CANCELDISCONTINUE: string = "CC_CA_MEDCANCEL";
        public static CA_AMEND: string = "AMEND";
        public static CA_REORDER: string = "REORDER";
        public static Lessthan: string = "CC_LS";
        public static LessthanOrEqualto: string = "CC_LSEQLTO";
        public static Greterthan: string = "CC_GRT";
        public static GreterthanOrEqualto: string = "CC_GRTEQLTO";
    }
    export class CActionTrigerredFrom {
        public static iDateTimePickerControl: string = "iDateTimePicker";
        public static iTimeBoxControl: string = "iTimeBox";
    }
    export class MedImage {
        public static GetPath(ImageSrc: string): string {
            return String.Concat("assets/images/", ImageSrc);
        }
    }
    export class MedImages {
        public static SteppedVariable: string = "iDoseTypeNOR16.png";
        public static White: string = "white1x1.png";
        public static RedStar: string = "ibubblestarnor16.png";
        public static MandatoryIndicator: string = "imandatoryindicator16.png";
        public static Amber: string = "ibubbleoptindnor16.png";
        public static Acknowledged: string = "iNewYes.png";
        public static DiscontinuedIcon: string = "idiscontinuedrugnor16.png";
        public static CancelIcon: string = "iNewCancelHot.png";
        public static HoldIcon: string = "iHoldNOR16.png";
        public static PendingIcon: string = "ipendingauth.png";
        public static CommentIcon: string = "icommenthot16.png";
        public static CheckedReadCheckIcon: string = "iCheckReadOnlyChecked13.png";
        public static CheckedReadUnCheckIcon: string = "iCheckReadOnlyUnchecked13.png";
        public static PGDAdministration: string = "pgd_prescription.png";
        public static CC_CARESET_ICO: string = "MPAD_Annotate_Active.png";
        public static CC_SUPINS_ICO: string = "Icon/iholdnor16.png";
        public static CC_ADDCOM_ICO: string = "iinfonor16.png";
        public static CC_OMIT_ICO: string = "slot status-omitted.png";
        public static CC_REVIEW_ICO: string = "iReviewAfterNOR16.png";
        public static CC_CNTRLDDRUG: string = "icontrolleddrugnor16.png";
        public static CC_UNLICENSED: string = "iunlicenseddrugnor16.png";
        public static CC_HIGHRISK: string = "iHighRiskNOR16.png";
        public static CC_NEWLY: string = "inewlymarketeddrugnor16.png";
        public static CC_NAMEDRUG: string = "inamedpatientdrugnor16.png";
        public static DoseTypeIcon: string = "idosetypenor16.png";
        public static FormviwerIcon: string = "iinfonor16.png";
        public static WarningIcon: string = "iwarninginfonor16.png";
        public static SelectionIcon: string = "icopyacrossnor24.png";
        public static LinkArrow: string = "iarrownor5x10.png";
        public static PowerArrow: string = "arrow.png";
        public static SelectionIconDIS: string = "icopyacrossdis24.png";
        public static Exclamation: string = "exclam.png";
        public static Star: string = "star.png";
        public static CompletedIcon: string = "completed.png";
        public static ImgFolderOpen: string = "itreefolderopen16.png";
        public static ImgFolderClose: string = "itreefolderclosedis16.png";
        public static ImgMltcmpnt: string = "Multicomponent Item.png";
        public static ImgOrderSet: string = "group_medicines_NOR16.png";
        public static MandatoryIcon: string = "conflict_01.png";
        public static SupplyrequestIcon: string = "Supply Flag_NOR16.png";
        public static ReviewAfterImage: string = "iinfonor16.png";
        public static ReviewAfterIcon: string = "iReviewAfterNOR16.png";
        public static WardStockIcon: string = "Wardstockitem16.PNG";
        public static ConflictPass: string = "ConflictPassCheck.png";
        public static WhiteQuestionMark: string = "ibubblequestionnor16.png";
        public static NoteIcon: string = "iCareEventsNOR16.png";
        public static DCIcon: string = "iCalculatorNOR16.png";
        public static DCIconWithAlert: string = "icalculatornor16_A.jpg";
        public static DCDisableIcon: string = "iCalculatorDIS16.png";
    }
    export class Conversion {
        public static minute: string = "minute";
        public static hour: string = "hour";
        public static day: string = "day";
        public static week: string = "week";
        public static month: string = "month";
        public static year: string = "year";
    }
    export class ConditionalDoseConstants {
        public static ObservationKey: string = "_OBSERVATION";
        public static ResultsKey: string = "_RESULTS";
        public static Numeric: string = 'N';
        public static Instruction: string = 'I';
    }
    export class AdditionalItemTypes {
        public static Observation: string = "Observation";
        public static Result: string = "Result";
    }
    export class StockRequisitionValue {
        public static NONWARDSTOCK: string = "CC_NONWARDSTOCK";
        public static WARDSTOCK: string = "CC_WARDSTOCK";
        public static RESUPPLY: string = "CC_RESUPPLY";
    }
    export class Roundoff {
        public static NEARESRHALF: string = "CC_HALFUNIT";
        public static NEARESTFULL: string = "CC_FULLUNIT";
        public static NONE: string = "CC_NONE1";
    }
    export class InfusionVolume {
        public static litre: string = "litre";
        public static microlitre: string = "microlitre";
        public static ml: string = "ml";
    }
    export class ConstDurationUOM {
        public static Days: string = "CC_MEDDRSN1";
        public static Weeks: string = "CC_MEDDRSN2";
        public static Months: string = "CC_MEDRSN3";
        public static Years: string = "CC_MEDRSN4";
        public static Minutes: string = "CC_MINUTES";
        public static Hours: string = "CC_HOURS";
        public static Doses: string = "CC_DOSES";
    }
    export class OtherDRCErrorCodes {
        public static DRCConditionalDose: string = "CC_NODRCCONDOSE1B";
        public static DRCTitratedDose: string = "CC_NODRCTITDOSE1C";
        public static DRCMCI: string = "CC_NODRCMCI1D";
        public static DRCTypeIn: string = "CC_NODRCCTYPEIN1E";
        public static DRCLocalDrug: string = "CC_NODRCLOCALMED1F";
        public static DRCMultiRoute: string = "CC_NODRCMCI1G";
        public static DRCPatientAge: string = "CC_NODRCPATAGE2A";
        public static DRCRoute: string = "CC_NODRCROUTE2B";
        public static DRCDose: string = "CC_NODRCDOSE2E";
        public static NoDRCResult: string = "CC_NODRCNOTSUPRT9";
        public static DRCSVChangingDose: string = "CC_SVCHANGDOSE";
    }
    export enum PrescribeSource {
        None = 0,

        DOS = 1,

        Other = 2
    }
    export class GPcStatus {
        public static Active: string = "Active";
        public static Completed: string = "Completed";
    }