name: Build Angular App

on:
  push:
    branches:
      - feature/epma-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List entire repo structure
        run: |
          ls -R > repo-structure.txt
          cat repo-structure.txt

      - name: Upload folder structure as artifact
        uses: actions/upload-artifact@v3
        with:
          name: folder-structure
          path: repo-structure.txt

      - name: Set working directory to epma
        run: echo "Switching to 'epma' folder"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: epma

      - name: Build Angular app
        run: npm run build -- --configuration=production
        working-directory: epma

      - name: Upload Angular build output
        uses: actions/upload-artifact@v3
        with:
          name: angular-build-output
          path: epma/dist/
