name: Build Angular App

on:
  push:
    branches:
      - feature/epma-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: epma

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show and save folder structure
        run: |
          ls -R ../ > ../repo-structure.txt
          cat ../repo-structure.txt

      - name: Upload folder structure artifact
        uses: actions/upload-artifact@v3
        with:
          name: folder-structure
          path: ../repo-structure.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Upload build output (optional)
        uses: actions/upload-artifact@v3
        with:
          name: angular-build-output
          path: dist/
